GET https://fullstackopen-3-bqkf.onrender.com/api/persons
###
POST https://fullstackopen-3-bqkf.onrender.com/api/persons
Content-Type: application/json

{
    "name":"Josan",
    "number":"782"
}
###
DELETE https://fullstackopen-3-bqkf.onrender.com/api/persons/4
###
GET https://fullstackopen-3-bqkf.onrender.com/info
